Service:
  RegionId: cn-hangzhou
  DeployType: ros
  DeployMetadata:
    SupplierDeployMetadata:
      RoleName: gushen-dataset-test
      UserType: Aliyun
      SupplierTemplateConfigs:
        - Name: Template
          Url: 'ros_templates/template.yaml'
          PredefinedParameters: []
          HiddenParameterKeys:
            - VpcId
            - VSwitchId
            - ZoneId
          ParameterMappings:
            - ParameterKey: RegionId
              ParameterMappingKeys:
                - VpcId
                - ZoneId
                - VSwitchId
              ParameterValueMapping:
                cn-hangzhou:
                  Parameters:
                    VpcId: vpc-bp1j3ie92jbgftbnbg92t
                    ZoneId: cn-hangzhou-i
                    VSwitchId: vsw-bp1oyaskfbk4z3vrg3yb6
      FileArtifactRelation:
        '{{ computenest::file::hanans426_mysql-managed-ack-demo }}':
          ArtifactId: ${Artifact.Artifact_1.ArtifactId}
          ArtifactVersion: ${Artifact.Artifact_1.ArtifactVersion}
  ServiceType: managed
  ServiceInfo:
    Locale: zh-CN
    ShortDescription: demo
    Image: 'resources/icons/service_logo.png'
Artifact:
  Artifact_1:
    ArtifactType: File
    ArtifactName: hanans426_mysql-managed-ack-demo
    ArtifactProperty:
      RegionId: cn-hangzhou
      Url: 'resources/artifact_resources/file/hanans426_mysql-managed-ack-demo.tar.gz'